config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'grinds#home'

  # grinds routes
  get 'grinds', to: 'grinds#home'
  get "grinds/new", to: "grinds#new", as: :new_grind
  post "grinds", to: "grinds#create"
  get "grinds/:id", to: "grinds#show", as: :grind
  delete "grinds/:id", to: "grinds#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grind.rb
class Grind < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/grinds_controller.rb
class GrindsController < ApplicationController
  skip_before_action :authenticate_user!
  def home
    @grinds = Grind.all
  end

  def show
    if (params[:id])
      @grind = Grind.find(params[:id])
    else
      redirect_to grind_path
    end
  end

  def new
    @grind = Grind.new
  end

  def create
    @grind = Grind.new(grind_params)
    @grind.save

    redirect_to grind_path(@grind)
  end

  def destroy
    @grind = Grind.find(params[:id])
    @grind.destroy

    redirect_to grind_path(@grind)
  end

  private
  def grind_params
    params.require(:grind).permit(:grinder_name, :grinder_setting, :coffee_name, :extraction_type, :comments, :grind_name)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/grinds/home.html.erb
<div class="container">
  <h1 class="main_title">Here you will find all your grinds</h1>

  <div class="new_grind_btn">
    <%= link_to "Log a new grind", new_grind_path, class: "btn btn-ghost" %>
  </div>

  <div class="cards">
    <% @grinds.each do |grind| %>
      <div class="card-category" >
        <div class="card-header">
          <p style="bold"><%= grind.grind_name %></p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Grinder: <%= grind.grinder_name %></li>
          <li class="list-group-item">Grinder setting: <%= grind.grinder_setting %></li>
          <li class="list-group-item">Coffee name: <%= grind.coffee_name %></li>
          <li class="list-group-item">Extraction type: <%= grind.extraction_type %></li>
          <li class="list-group-item">Comments: <%= grind.comments %></li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/grinds/index.html.erb
<div class="container">
  <h1>Here you will find all your grinds</h1>

<button type="button" class="btn btn-outline-secondary"> <%= link_to "Log a new grind", new_grind_path %>
</button>

  <div class="card" style="width: 18rem;">
  <% @grinds.each do |grind| %>
    <div class="card-header">
    <p style="bold"><%= grind.grind_name %></p>
    </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Grinder: <%= grind.grinder_name %></li>
        <li class="list-group-item">Grinder setting: <%= grind.grinder_setting %></li>
        <li class="list-group-item">Coffee name: <%= grind.coffee_name %></li>
        <li class="list-group-item">Extraction type: <%= grind.extraction_type %></li>
        <li class="list-group-item">Comments: <%= grind.comments %></li>
      </ul>
    <% end %>
  </div>
</div>

app/views/grinds/new.html.erb
<div class="container">
  <h3 class="main_title">Remember, remember that grind last december</h3>

  <div class="new-grind-card">
    <div class="card w-50">
      <div class="card-category">
        <%= form_for(@grind) do |f| %>
          <ul class="list-group list-group-flush">
            <%= f.label :grind_name %>
            <%= f.text_field :grind_name %>
            <%= f.label :grinder_name %>
            <%= f.text_field :grinder_name %>
            <%= f.label :grinder_setting %>
            <%= f.number_field :grinder_setting %>
            <%= f.label :coffee_name %>
            <%= f.text_field :coffee_name %>
            <%= f.label :extraction_type %>
            <%= f.text_field :extraction_type %>
            <%= f.label :comments %>
            <%= f.text_field :comments %>
          </ul>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="back_to_home_btn">
    <%= link_to "Back to your grinds", grinds_path, class: "btn btn-ghost" %>
  </div>


</div>

app/views/grinds/show.html.erb
<div class="container">
  <div class="new_container">
    <div class="card" style="width: 25rem;">
      <%= image_tag("card_badge.jpg") %>
      <div class="card-body">
        <h3 class="card-title"><u>This is what you did.</u></h3>
        <h3 class="card-text"><%= @grind.grind_name %></h3>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Coffee name: <%= @grind.coffee_name %></li>
        <li class="list-group-item">Extraction type: <%= @grind.extraction_type %></li>
        <li class="list-group-item">What you thought: <%= @grind.comments %></li>
      </ul>
      <div class="card-body">
        <%= link_to "Back to your grinds", grinds_path %>
        <%= link_to "Delete", grind_path(@grind), method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DialerAll</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag("coffee_grinder_logo.jpg") %>
  <% end %>

  <h1>Dialerall</h1>
  <h3>You dial, I'll recall it.</h3>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>